version: '3'

services:
  python-dev:
    container_name: python-dev
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    tty: true